### ISSUE TITLE
Multiple include in JavaScript Antlr example

### ISSUE THREAD

**Issue by amir734jj** [kaby76/AntlrExamples#3]
```
<ItemGroup>
<Antlr4 Include="JavaScriptLexer.g4" />
<Antlr4 Include="JavaScriptParser.g4" />
<Antlr4 Include="JavaScriptLexer.g4" />
<Antlr4 Include="JavaScriptParser.g4" />
</ItemGroup>
```

Its probably a typo

[Source](https://github.com/kaby76/AntlrExamples/blob/master/Javascript/C%23/Test.csproj#L9)

**Comment by kaby76** [comment]
I've updated the code to use the latest [JavaScript grammar[(https://github.com/antlr/grammars-v4/tree/master/javascript/javascript) from the [grammars-v4](https://github.com/antlr/grammars-v4) repo and the latest driver generated by [trgen](https://github.com/kaby76/Domemtech.Trash/tree/main/trgen). The duplicate references to the grammars are no longer there.

**Comment by amir734jj** [comment]
@kaby76  Thank you :)
